/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/top": {
    /** List top searches */
    get: {
      responses: {
        /** @description Successful operation */
        200: {
          content: {
            "application/json": components["schemas"]["TopSearchPayload"];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/users/{userId}/top": {
    /** List top searches of a user */
    get: {
      parameters: {
        path: {
          /** @description The user to filter by */
          userId: string;
        };
      };
      responses: {
        /** @description Successful operation */
        200: {
          content: {
            "application/json": components["schemas"]["TopSearchPayload"];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    TopSearchPayload: ({
        country: string;
        value: number;
        percentage: number;
      })[];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
